Sage-Bionetworks/scicomp-infra

.travis.yml
create_cf_stack.sh

Allow travis to provision EC2 instances when new stacks
are added to create_cf_stack.sh script.
Workflow:
1. git checkout -b new-instance
2. User (jsmith) adds a new stack to create_cf_stack.sh file.
3. git commit -a -m "create instance for anxiety study"
4. git push origin new-instance
5. Create a PR on github
6. Have someone review and approve the PR
7. PR is approved and merged
8. Travis provisions a new EC2 instance
9. jsmith can now login with his jumpcloud credentials

Setup auto provisioning of EC2 instances

---

cf_templates/jumpcloud.yml
update_cf_stack.sh

A resource (i.e. EC2 instance) is provisioned with a CF stack and it
gets registered as a "system" in jumpcloud.  When the resource is removed
from AWS (via a stack delete) it will continue to be registered on jumpcloud.
We add this lambda to periodically clean up those registered systems on
jumpcloud.

Lambda to cleanup jumpcloud systems

---

cf_templates/ec2.yml
provision_utils.sh

I would like the ability to use the auto-provisioner to provision an instance in the public subnet. From what I see the ec2.yml supports it. This PR surfaces the parameter to the provisioning function so it can be used in create_cf_stack.sh.

Add subnet param

---

cf_templates/accounts.yml

PowerUserAccess policy is too limited when accessing IAM.  It only
allows viewing roles but does not allow viewing groups, policies
or users.  Adding 'IAMReadOnlyAccess' will provide view only access
IAM info.

Update AWS developer group permissions

---

auto-provision/DeleteSynapseExternalBucket.sh

This script is for deleting the Synapse external bucket and
the related stack that provisioned that bucket.  It is meant
to be run manually using the admin role.

Delete the synapse external bucket stack

---

templates/SynapseExternalBucket.yaml

Create bucket without encryption by default.  Encryption can be enabled
by setting the parameter EncryptBucket="true"

Make bucket encryption optional

---

auto-provision/SynapseExternalBucketHelper.sh

Uploading files to an encrypted bucket with the aws cli requires the
`--sse aws:kms` option.

fix uploading owner.txt file

---

auto-provision/SynapseExternalBucketHelper.sh

Apparently you can upload an encrypted file to a non-encrypted
bucket.  Change to not specify encryption so file is uploaded
without encryption when uploading to non-encrypted bucket.

fix synapse uploading of owner.txt file

---

templates/accounts.yaml

AWS Batch doesn't work for Thomas, it just hangs when attempting
to create a batch.  We think it's because the Developers group is
lacking the permissions.  Provide full batch access to the group
as a test.

Give developers AWS batch access

---

auto-provision/SynapseExternalBucketHelper.sh
config/prod/test-kdaily-encryptedexternals3.yaml
config/prod/test-kdaily-encryptedexternals6.yaml
config/prod/test-kdaily-unencryptedexternals3.yaml
config/prod/test-kdaily-unencryptedexternals5.yaml
hooks/synapse_external_bucket.py
templates/SynapseExternalBucket.yaml

* Sceptre hook to setup external bucket which will replace the
SynapseExternalBucketHelper.sh script.
* Instead of searching in git log for committer email just have
the user specify the email (OwnerEmail) to send the bucket info to.
Relying on the email in git log can be error prone, people may not
even setup an email in their git config.
* Make SynapseExternalBucketHelper.sh script compatible until it gets
removed
* Update existing synapse bucket deployments with OwnerEmail parameter

add hook to setup synapse external bucket

---

.travis.yml

This prevents travis from deploying when PRs are created from
the github UI.

only deploy changes from master branch

---

config/prod/test-ki-rally-manager-ec2.yaml

This is a testing ec2 for a Gates ki project. It will be used with Synapse workflows to connect an external database with an evaluation queue to manage the creation of Synapse objects (projects, teams, tables) to support Gates Foundation HBGDki rallies and sprints.

add config for testing ki rally manager ec2

---

config/prod/test-bsmn-cfncluster-ec2.yaml

A privately accessible ec2 for testing a cfncluster installation.

add config for ec2 for bsmn pipeline

---

templates/accounts.yaml

The idea to resolving issue IT-423 is to send Agora logs to an
external log analysis service (sumologic) and give consultants
access to the logs in sumologic instead of in the scicomp
AWS account.

[IT-423] allow consultants access to agora logs

---

config/prod/sumologic-role.yaml

Sumo logic recommends setting up a role to allow access to the S3
buckets in our AWS account.  This is to allow sumo to ingest
logs from those buckets

[IT-423] Setup sumo logic role

---

config/prod/RotateCredentials.yaml

This reverts commit 2a176c165f70a1eaea0525c0aeaca0f34cf50f2d.
RotateCredentials has been restored on git with PR https://github.com/Sage-Bionetworks/aws-infra/pull/79

Revert "fix deployment of RotateCredentials.yaml"

---

templates/accounts.yaml

Due to the limitations of batch policies[1] we cannot scope user access
to specific actions on specific batch jobs.  Therefore we need to provide
broder access to make it usable to a batch developer.  Adding a batch
developer group for Tom so he can develop and trigger batch jobs from
the AWS console.
Note-this group would have access to all batch resources not just the
ones they created.
[1] https://docs.aws.amazon.com/batch/latest/userguide/batch-supported-iam-actions-resources.html

Add a batch developer group

---

templates/accounts.yaml

I can't think of a good way to allow users without scicomnp accounts
to create AMIs from their provisioned EC2 instances.  Therefore we
will setup a group to allow scientific team leads to help create AMIs
for scicomp users.

Add a science team lead group

---

templates/accounts.yaml

Access will be used to monitor performance of toil cluster so that we can fine-tune workflow performance.

Provide William Poehlman with read-only access to scicomp account

---

templates/accounts.yaml

Cloudformation does not support Resource Groups[1] feature
yet so we give Tess access to manually setup resource groups
from the AWS console
[1] https://docs.aws.amazon.com/ARG/latest/userguide/welcome.html

Give Tess access to Resource Groups

---

config/prod/s3-computevpc-gateway-endpoint.yaml
config/prod/s3-snowflakevpc-gateway-endpoint.yaml

Setup a gateway vpc endpoint so that EC2 instances can directly access
other resources in the same VPC S3 buckets instead of having to go out
to the internet to access the same resources. This will reduce network
latency and cost since the EC2 doesn't need to go out thru the NAT
gateway.
This depends PR https://github.com/Sage-Bionetworks/aws-infra/pull/171

gateway vpc endpoint for computevpc and snowflakevpc

---

templates/accounts.yaml

Add the ability to describe tags so that when assuming AWSCapacityReservationPolicy, one may look up the tags for an instance id. These tags will be applied to a new capacity reservation being made.

Add DescribeTags to AWSCapacityReservationPolicy

---

config/prod/cloudwatch-cross-account-sharing.yaml

Allow users in org-sagebase-sandbox account to view org-sagebase-scicomp
account's cloudwatch dashboard and logs.
This depends on PR https://github.com/Sage-Bionetworks/aws-infra/pull/218

permit sandbox users to view scicomp's cloudwatch

---

config/prod/cloudwatch-cross-account-sharing.yaml

Allow users in org-sagebase-sandbox account to view org-sagebase-scicomp
account's cloudwatch dashboard and logs.
This depends on PR https://github.com/Sage-Bionetworks/aws-infra/pull/218

permit sandbox users to view scicomp's cloudwatch (#208)

---

config/prod/jumpcloud-idp.yaml
templates/jumpcloud-idp.yaml

Setup a jumpcloud app to allow scientist read only access to
scicomp so they can validate that their apps are installed correctly
and they can view cloudwatch info for their running apps.

Setup a jumpcloud read only app

---

config/prod/AccountAlertTopics.yaml
config/prod/bootstrap.yaml
config/prod/cfn-cr-saml-provider.yaml
config/prod/cfn-s3objects-macro.yaml
config/prod/cloudwatch-cross-account-sharing.yaml
config/prod/computevpc.yaml
config/prod/essentials.yaml
config/prod/guardduty-member.yaml
config/prod/park-my-cloud.yaml
config/prod/peer-vpn-computevpc.yaml
config/prod/peer-vpn-snowflakevpc.yaml
config/prod/rotate-credentials.yaml
config/prod/s3-computevpc-gateway-endpoint.yaml
config/prod/s3-snowflakevpc-gateway-endpoint.yaml
config/prod/sage-tgw-computevpc.yaml
config/prod/sage-tgw-snowflakevpc.yaml
config/prod/sagebionetworks-org-acm-cert.yaml
config/prod/service-linked-roles.yaml
config/prod/snowflakevpc.yaml
config/prod/sumologic-role.yaml

This repo had several config files containing a `before_update` hook but not a matching `before_create` hook (see, for example, config/prod/computevpc.yaml). I tried changing the lone `before_update`'s to `before_launch`'s. I don't know enough to be sure that that is not going to have unintended consequences, so please pay extra attention to this issue in review.

Change Sceptre Hooks to before_launch

---

templates/jumpcloud-idp.yaml

The built in "arn:aws:iam::aws:policy/ReadOnlyAccess" does not provide
enough permissions to view databases.  When read only users search
for Document DBs they get the following message:
"not authorized to perform: rds:DescribePendingMaintenanceActions with an explicit deny"
Explicity give read access to DBs.

Give scicop viewers read access to Doc DBs

---

templates/jumpcloud-idp.yaml

The more appropriate policy for an account viewer is the
ViewOnlyAccess policy.

Update viewer policy

---

templates/jumpcloud-idp.yaml

This reverts commit 8d1d4205cfcc0e3dd8e7481490ff7fb282d4fb0c.
The power user policy already provides full batch access

Revert "Give AWS developers users access to batch (#220)"

---

templates/jumpcloud-idp.yaml

Give scicomp-viewer users access to view access to Elastic Beanstalk.
The purpose is to allow application developers to view beanstalk
application logs to make sure apps are updated and running as
expected.

elastic beanstalk view access
