Sage-Bionetworks/scicomp-infra

- cf_templates/ec2.yml
- create_cf_stack.sh
Parameterize tags and make them a required parameter.  The committer
is the owner of the resource because he made the commit to provision
new resource.
> parameterize tags

- create_cf_stack.sh
Setup the CI to email the instance IP address to the owner of the
provisioned resource.  The CI is actually using AWS SES to send
emails to the committer.  SES was setup prior to this commit.
> Setup CI to email instance ip

- create_cf_stack.sh
Delete stacks that have been removed from create_cf_stacks.sh script.
> De-provision stacks

- provision_utils.sh
Prepend stack names with "ap-" so we can better identify them.
> prepend stack names

- .gitignore
- .travis.yml
- config/prod/accounts.yaml
- config/prod/bootstrap.yaml
- config/prod/config.yaml
- config/prod/essentials.yaml
- config/prod/jumpcloud.yaml
- config/prod/peer-route-config.yaml
- config/prod/vpc.yaml
- templates/accounts.yaml
- templates/ec2.yaml
- templates/jumpcloud.yaml
- validate-templates.sh
Use sceptre[1] to deploy CF templates.
[1] https://sceptre.cloudreach.com/latest/about.html
> Refactor CF stack deployments

- auto-provision/SynapseExternalBucketHelper.sh
- templates/SynapseExternalBucket.yaml
Create the infrastructure to create and provision synapse
external buckets[1] in aws scicomp account.
[1] http://docs.synapse.org/articles/custom_storage_location.html
> [Resolve IT-255] Synapse External bucket template

- config/prod/GatesKI-TestStudy.yaml
This reverts commit 492f4362954ec5a8e7a42f435c7c58016a033609.
> Revert "test synapse extneral bucket (#76)"

- config/prod/test-kdaily-encryptedexternals3.yaml
A test bucket with encryption for use with Synapse as an external storage location. Will delete this later.
> Test encrypted bucket

- config/prod/test-kdaily-unencryptedexternals3.yaml
testing with unencrypted bucket
> add unencrypted bucket test

- hooks/synapse_external_bucket.py
Default parameters allows the user to optionally specify them in
sceptre.  If the parameter is not specified in a sceptre stack config
file reading the parameter in the hook will fail.  We need to
read the parameters from CF because that will always contain the
default value if it's not explicitly set in a sceptre config.
> Refactor to account for default parameters

- templates/accounts.yaml
* Add a billing manager group and add khai and Xa to it.
* Tom is now developing in the new sandbox account so we
can lower his access to read only on scicomp.
> update aws account groups

- config/prod/AMP-WGS-MSSM-Transfer.yaml
@zaro0508 Would you please merge?
> added AMP-WGS-MSSM-Transfer bucket

- templates/SynapseExternalBucket.yaml
Provide the user with the option to enable a glacier life cyle rule
on a synapse external bucket.
> [IT-290] Glacier life cycle

- templates/SynapseExternalBucket.yaml
Add a parameter to allow users to enable versioning on their
synapse external buckets
> versioning for synapse external buckets

- hooks/notify_ec2.py
- templates/managed-ec2.yaml
Setup scripts to allow users to submit a PR to provision
new EC2 instances.
> Setup EC2 auto provisioning

- config/prod/raad2-challenge.yaml
- config/prod/test-hipaa.yaml
Define AMI with encrypted boot volume
> HIPAA compliant boot volume

- config/prod/snowflakevpc.yaml
Create a snowflake VPC for custom apps that wan to run in scicomp.
> create VPC for snowflake apps

- config/prod/peer-vpn-snowflakevpc.yaml
Peer the snowflakevpc with our VPN gateway[1] so we can manage network
access from the VPN.
[1] https://github.com/Sage-Bionetworks/admincentral-infra/blob/master/README.md#vpn-gateway
> snowflakevpc peering to the VPN

- templates/accounts.yaml
Reverts Sage-Bionetworks/scicomp-infra#188
> Revert "Add batch admin"

- templates/accounts.yaml
I believe Tess is done debugging toil on scicomp so we should
now revoke her permission.
> revoke Tess permissions

- config/prod/service-linked-roles.yaml
This depends on PR https://github.com/Sage-Bionetworks/aws-infra/pull/161
> Setup service linked role to provision EC2 spot instances.

- config/prod/service-linked-roles.yaml
Global template was fixed with PR https://github.com/Sage-Bionetworks/aws-infra/pull/162
> 2nd attempt at deploying service linked roles

- templates/accounts.yaml
@zaro0508 @ahayden Proposal to allow view cost and usage reports.
> Add policy to view usage and billing reports, and assign policy

- templates/accounts.yaml
Based on convesation in sageit slack channel, create a role to work with capacity reservations, and add Tess's account to it.
> Created AWSCapacityReservationRole, added Tess's account to principals

- config/prod/cfn-s3objects-macro.yaml
Deploy macro in PR https://github.com/Sage-Bionetworks/aws-infra/pull/211
> deploy cloudformation s3objects macro
